/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;


/**
 *
 * @author Amarjeet
 */
public class CheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
         SimpleDateFormat myFormat= new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal=Calendar.getInstance();
        String today=myFormat.format(cal.getTime());
        jTextFieldCheckOut.setText(today);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldRoomNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCheckIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCheckOut = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMobileNumber = new javax.swing.JTextField();
        jTextFieldNumberOfDay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotalAmt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPricePerDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(60, 130));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 80, -1, -1));
        getContentPane().add(jTextFieldRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 82, 291, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 80, 135, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 141, -1, -1));
        getContentPane().add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 173, 209, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Check In Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 141, 104, -1));
        getContentPane().add(jTextFieldCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 173, 225, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Check Out Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 141, -1, -1));
        getContentPane().add(jTextFieldCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 173, 213, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 141, -1, -1));
        getContentPane().add(jTextFieldMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 173, 212, 30));
        getContentPane().add(jTextFieldNumberOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 241, 213, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 209, -1, -1));
        getContentPane().add(jTextFieldTotalAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 241, 212, 31));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Price Per Day");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 209, -1, -1));
        getContentPane().add(jTextFieldPricePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 241, 209, 31));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText(" Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 209, 104, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 241, 225, 31));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Number Of Days Stay");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 209, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Check Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 306, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 306, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Mobile No.", "Gender", "Email", "Id Proof", "Id Proof No.", "Address", "City", "State", "Nation", "Beds", "Room Type", "Room No.", "Price Per Day", "Check In Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1230, 230));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/Close.jpeg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/CheckOut.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        String query="select * from CheckIn where checkoutdate is null";
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        
        try
        {
           ResultSet set=Select.getData(query);
           while(set.next())
           {
               model.addRow(new Object[] {set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),
                   set.getString(8),set.getString(9),set.getString(10),set.getString(11),beds=set.getString(12),roomType=set.getString(13),set.getString(14),set.getString(15),set.getString(16)});
               
           }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown
     int id=0;
     String name="";
     String mobile="";
     String checkindate="";
     String price="";
     String roomNum="";
     String roomType="";
     String beds="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         roomNum=jTextFieldRoomNumber.getText();
        String query="select * from CheckIn where rmnum='"+roomNum+"'";
        try
        {
            ResultSet set=Select.getData(query);
            if(set.next())
            {
                id=set.getInt(1);
                jTextFieldFirstName.setText(name=set.getString(2));
                jTextFieldCheckIn.setText(checkindate=set.getString(16));
                jTextFieldMobileNumber.setText(mobile=set.getString(3));
                jTextFieldPricePerDay.setText(price=set.getString(15));
                jTextFieldEmail.setText(set.getString(5));
                try
                {
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
                    java.util.Date checkOutDate=sdf.parse(jTextFieldCheckOut.getText());
                    java.util.Date checkInDate=sdf.parse(jTextFieldCheckIn.getText());
                    long DiffInMilliSec=checkOutDate.getTime()-checkInDate.getTime();
                    int daysDiff=(int) DiffInMilliSec/(1000*60*60*24);
                    if(daysDiff==0)
                        daysDiff=1;
                    jTextFieldNumberOfDay.setText(String.valueOf( daysDiff));
                    double price=Double.parseDouble(jTextFieldPricePerDay.getText())*daysDiff;
                    jTextFieldTotalAmt.setText(String.valueOf(price));
                }
                catch(ParseException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Room Not Booked");
                setVisible(false);
                new CheckOut().setVisible(true);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          String checkOutDate=jTextFieldCheckOut.getText();
          String days=jTextFieldNumberOfDay.getText();
          String amt=jTextFieldTotalAmt.getText();
          String query="update CheckIn set staydays='"+days+"',Totalamt='"+amt+"',checkoutdate='"+checkOutDate+"'where cid='"+id+"'";
          InUpDel.setData(query, "");
          String roomNum=jTextFieldRoomNumber.getText();
          query="update Room set Status='Not Booked' where R_Number='"+roomNum+"'";
          InUpDel.setData(query, "");
          String path="F:\\";
          com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
          try
          {
              PdfWriter.getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
              doc.open();
              Paragraph p1=new Paragraph("***************************************************************************************************");
              doc.add(p1);
              
              Paragraph p2=new Paragraph("                                         PAN PACIFIC HOTEL AND RESORTS\n");
              doc.add(p2);
              doc.add(p1);
              //Customer Details
              Paragraph p3=new Paragraph("Bill Id         : "+id+"\n");
              doc.add(p3);
              Paragraph p4=new Paragraph("Customer Name   : "+name+"\n");
              doc.add(p4);
              Paragraph p5=new Paragraph("Mobile No.      : "+mobile+"\n");
              doc.add(p5);
              doc.add(p1);
              //---------------------------Room Details----------------------
               Paragraph p6=new Paragraph("Room No.       :" +roomNum+"\n");
              doc.add(p6);
              Paragraph p7=new Paragraph("Room Type       :"+roomType+"\n");
              doc.add(p7);
              Paragraph p8=new Paragraph("No. Of Beds     :"+beds+"\n");
              doc.add(p8);
              doc.add(p1);
              //------------------------Billing Details----------------------
              PdfPTable tb1=new PdfPTable(5);
              tb1.addCell("Check-In Date    :"+checkindate);
              tb1.addCell("Check-Out Date   :"+checkOutDate);
              tb1.addCell("Stay Days        :"+days);
              tb1.addCell("Price Per Day    :"+price);
              tb1.addCell("Total Amount     :"+amt);
               doc.add(tb1);
               //----------------------------footer---------------------------
                doc.add(p1);
                Paragraph p9=new Paragraph("                                               Thank you, Please Visit Again.\n");
                doc.add(p9);
                doc.add(p1);
                 
                //-----------------Receipt Completed------------
          }
          catch(DocumentException | FileNotFoundException e)
          {
              JOptionPane.showMessageDialog(null, e);
          }
          doc.close();
          int a=JOptionPane.showConfirmDialog(null, "Do You Want Print Bill?","Select",JOptionPane.YES_NO_OPTION);
          if(a==0)
          {
              try
              {
                  if((new File("F:\\"+id+".pdf")).exists())
                  {
                      Process p=Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler F:\\"+id+".pdf");
                  }
                  else
                  {
                      System.out.println("File Do Not Exist");
                  }
              }
              catch(IOException e)
              {
                  JOptionPane.showMessageDialog(null, e);
              }
          }
          setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCheckIn;
    private javax.swing.JTextField jTextFieldCheckOut;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldMobileNumber;
    private javax.swing.JTextField jTextFieldNumberOfDay;
    private javax.swing.JTextField jTextFieldPricePerDay;
    private javax.swing.JTextField jTextFieldRoomNumber;
    private javax.swing.JTextField jTextFieldTotalAmt;
    // End of variables declaration//GEN-END:variables
}
