/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import javax.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Amarjeet
 */
public class ForgetPass extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPass
     */
    public ForgetPass() {
        initComponents();
        hideMenu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void hideMenu()
    {
     
      jTextFieldQuestion.setVisible(false);
      jTextFieldAns.setVisible(false);
      jTextFieldNewpass.setVisible(false);
      
      
      jLabelQue.setVisible(false);
      jLabelAns.setVisible(false);
      jLabelNewP.setVisible(false);
      jButtonReset.setVisible(false);
    }
     private void showMenu()
    {
     
      jTextFieldQuestion.setVisible(true);
      jTextFieldAns.setVisible(true);
      jTextFieldNewpass.setVisible(true);
      
      
      jLabelQue.setVisible(true);
      jLabelAns.setVisible(true);
      jLabelNewP.setVisible(true);
       jButtonReset.setVisible(true);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAns = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jTextFieldQuestion = new javax.swing.JTextField();
        jTextFieldNewpass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelQue = new javax.swing.JLabel();
        jLabelAns = new javax.swing.JLabel();
        jLabelNewP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Forgot Password");

        jTextFieldAns.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldAns.setText("Answer");
        jTextFieldAns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextFieldAns.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAnsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAnsFocusLost(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldUser.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser.setText("Enter your username to search");
        jTextFieldUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextFieldUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUserFocusLost(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(255, 51, 0));
        jButtonReset.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jButtonReset.setText("Reset Password");
        jButtonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextFieldNewpass.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNewpass.setText("New Password");
        jTextFieldNewpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNewpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNewpassFocusLost(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/username.png"))); // NOI18N

        jLabelQue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/question.png"))); // NOI18N

        jLabelAns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/Ans.png"))); // NOI18N

        jLabelNewP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/lock.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelQue)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAns)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNewP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldAns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                                .addComponent(jTextFieldNewpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButtonReset)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldUser)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelQue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAns))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAns, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNewP))
                .addGap(37, 37, 37)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("        X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String Username=jTextFieldUser.getText().trim();
        String Query="select * from users where U_NAME=?";
        try
        {
            Connection con=ConnectToDb.connect();
            PreparedStatement p=con.prepareStatement(Query);
            p.setString(1, Username);
            ResultSet set=p.executeQuery();
            if(set.next())
            {
                JOptionPane.showMessageDialog(null,"User Found","Success",1);
                showMenu();
                String sq=set.getString(4);
                jTextFieldQuestion.setText(sq);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "User not found","Please Enter Another Username",2);
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
       
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        String Query="select U_ID from users where U_NAME=? and SecurityQ=? and Answer=?";
        String User=jTextFieldUser.getText();
        String SecurityQ=jTextFieldQuestion.getText();
        String Ans=jTextFieldAns.getText();
        try
        {
            Connection con=ConnectToDb.connect();
            PreparedStatement p=con.prepareStatement(Query);
            p.setString(1, User);
            p.setString(2, SecurityQ);
            p.setString(3, Ans);
            ResultSet set=p.executeQuery();
            
            if(set.next())
            {
                String query="update users set U_PASSWORD=? where U_ID=?";
                p=con.prepareStatement(query);
                p.setString(1,jTextFieldNewpass.getText());
                p.setInt(2,set.getInt(1));
                int r=p.executeUpdate();
                if(r>0)
                {
                    JOptionPane.showMessageDialog(null, "Password Changed","Success",1);
                     new Login().setVisible(true);
                     this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Wrong Answer","Please Try Again",2);
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextFieldUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserFocusGained
        // TODO add your handling code here:
        
        if(jTextFieldUser.getText().trim().equalsIgnoreCase("Enter your Username to search"))
        {
            jTextFieldUser.setText("");
            jTextFieldUser.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldUserFocusGained

    private void jTextFieldUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserFocusLost
        if(jTextFieldUser.getText().trim().equalsIgnoreCase("Enter your Username to search")||jTextFieldUser.getText().trim().equalsIgnoreCase(""))
        {
            jTextFieldUser.setText("Enter your Username to search");
            jTextFieldUser.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldUserFocusLost

    private void jTextFieldAnsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAnsFocusGained
        // TODO add your handling code here:
        if(jTextFieldAns.getText().trim().equalsIgnoreCase("Answer"))
        {
           jTextFieldAns.setText("");
           jTextFieldAns.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldAnsFocusGained

    private void jTextFieldAnsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAnsFocusLost
        // TODO add your handling code here:
        if(jTextFieldAns.getText().trim().equalsIgnoreCase("Answer")||jTextFieldAns.getText().trim().equalsIgnoreCase(""))
        {
            jTextFieldAns.setText("Answer");
           jTextFieldAns.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldAnsFocusLost

    private void jTextFieldNewpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNewpassFocusGained
        // TODO add your handling code here:
         if(jTextFieldNewpass.getText().trim().equalsIgnoreCase("New Password"))
        {
           jTextFieldNewpass.setText("");
           jTextFieldNewpass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldNewpassFocusGained

    private void jTextFieldNewpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNewpassFocusLost
        // TODO add your handling code here:
         if(jTextFieldNewpass.getText().trim().equalsIgnoreCase("New Password")|| jTextFieldNewpass.getText().trim().equalsIgnoreCase(""))
        {
             jTextFieldNewpass.setText("New Password");
             jTextFieldNewpass.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldNewpassFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAns;
    private javax.swing.JLabel jLabelNewP;
    private javax.swing.JLabel jLabelQue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAns;
    private javax.swing.JTextField jTextFieldNewpass;
    private javax.swing.JTextField jTextFieldQuestion;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
